[package]
name = "magni-auth"
version = "0.1.0"
authors = ["joseph <12-10424@usb.ve>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel = "*"
mongodb = "*"
bson = "*"
rustc-serialize = "*"
